# Generated by Django 5.2 on 2025-04-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from external API (e.g., Ticketmaster)', max_length=100, null=True),
        ),
    ]
