# Generated by Django 4.2.20 on 2025-04-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from external API (e.g., Ticketmaster)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, help_text='Original image URL from external source', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
