# Generated by Django 5.2 on 2025-04-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, help_text='Original image URL from external source'),
        ),
    ]
