# Generated by Django 5.2 on 2025-04-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail version of the image', null=True, upload_to='events/thumbnails/'),
        ),
    ]
