# Generated by Django 4.2.20 on 2025-04-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spotify_followers',
            field=models.IntegerField(blank=True, help_text='Number of Spotify followers', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(blank=True, help_text='Spotify artist ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_image_url',
            field=models.URLField(blank=True, help_text='URL to artist image on Spotify', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_last_updated',
            field=models.DateTimeField(blank=True, help_text='When Spotify data was last updated', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_popularity',
            field=models.IntegerField(blank=True, help_text='Spotify artist popularity score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_uri',
            field=models.CharField(blank=True, help_text='Spotify artist URI', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_url',
            field=models.URLField(blank=True, help_text='Spotify artist URL', max_length=1000, null=True),
        ),
    ]
