[project]
name = "musicevents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "django==5.2",
    "pillow>=11.2.1",
    "pytz>=2025.2",
    "requests>=2.32.3",
    "ruff>=0.11.6",
]
