apiVersion: v1
kind: Secret
metadata:
  name: {{ include "musicevents.fullname" . }}
  labels:
    {{- include "musicevents.labels" . | nindent 4 }}
type: Opaque
data:
  ticketmaster-api-key: {{ .Values.ticketmasterApiKey | b64enc | quote }}
  django-secret-key: {{ .Values.djangoSecretKey | default (randAlphaNum 32) | b64enc | quote }}
  spotify-client-id: {{ .Values.spotifyClientId | b64enc | quote }}
  spotify-client-secret: {{ .Values.spotifyClientSecret | b64enc | quote }}
  
  # Database URL
  database-url: {{ .Values.databaseUrl | b64enc | quote }}
  
  # Admin credentials
  admin-username: {{ .Values.adminUsername | b64enc | quote }}
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
  admin-email: {{ .Values.adminEmail | b64enc | quote }}