apiVersion: v1
kind: Secret
metadata:
  name: {{ include "musicevents.fullname" . }}
  labels:
    {{- include "musicevents.labels" . | nindent 4 }}
type: Opaque
data:
  ticketmaster-api-key: {{ .Values.ticketmasterApiKey | b64enc | quote }}
  django-secret-key: {{ .Values.djangoSecretKey | default (randAlphaNum 32) | b64enc | quote }}